SSWFProject/Models/MealBoxViewModel.cs
using Domain;

namespace Portal.Models
{
    public class MealBoxViewModel
    {
        public IEnumerable<MealBox> MealBoxes { get; set; } = Enumerable.Empty<MealBox>();
    }
}

SSWFProject/Controllers/MealBoxController.cs
using Domain;
using DomainServices;
using DomainServices.Rules;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Portal.Models;
using SSWFProject.Models;
using System.Collections.ObjectModel;
using System.Diagnostics;

namespace Portal.Controllers
{
    public class MealBoxController : Controller
    {
        private readonly IMealBoxRepository _repository;
        private readonly IEmployeeRepository _employeeRepository;
        private readonly IProductRepository _productRepository;
        private readonly IStudentRepository _studentRepository;
        private readonly IMealBoxReservationService _mealBoxReservationService;

        public MealBoxController(IMealBoxRepository repository, IEmployeeRepository employeeRepository, IProductRepository productRepository, IStudentRepository studentRepository, IMealBoxReservationService mealBoxReservationService)
        {
            _repository = repository;
            _employeeRepository = employeeRepository;
            _productRepository = productRepository;
            _studentRepository = studentRepository;
            _mealBoxReservationService = mealBoxReservationService;
        }

        public IActionResult MealBoxes(int? id)
        {
            if(id == null)
            {
                var viewModel = new MealBoxViewModel
                {
                    MealBoxes = _repository.Mealboxes,
                };
                return View("MealBoxes", viewModel);
            }
            var mealbox = _repository.GetMealBoxById(id.Value);
            if(mealbox == null)
            {
                return NotFound();
            }

            return View("MealBoxDetail", mealbox);
        }

        [HttpPost]
        public IActionResult MealBox(int id)
        {
            _repository.DeleteMealBox(id);
            return RedirectToAction("Admin", "Account");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Create()
        {
            var employee = _employeeRepository.GetEmployeeByNr(User.Identity!.Name!);
            ViewBag.CreateCityChoice = employee?.Cantina.City;
            ViewBag.CantinaServesWarm = employee?.Cantina.ServesWarm;
            ViewBag.CreateLocationChoice = employee?.Cantina.Location;

            List<ProductViewModel> productViewModels = new List<ProductViewModel>();

            foreach(Product p in _productRepository.Products)
            {
                productViewModels.Add(new ProductViewModel { Product = p, isSelected = false});
            }

            var viewModel = new CreateUpdateMealBoxViewModel
            {
                MealBox = new MealBox(),
                ProductViewModels = productViewModels,
            };

            return View("CreateBox", viewModel);
        }

        [HttpPost]
        public IActionResult Create(CreateUpdateMealBoxViewModel cbvm)
        {
            MealBox? mealBox = cbvm.MealBox;
            mealBox.PickupFromTime = DateTime.Now;
            mealBox.Products = new List<Product>();
            var employee = _employeeRepository.GetEmployeeByNr(User.Identity!.Name!);
            mealBox.Cantina = employee.Cantina;

            IList<ProductViewModel> productViewModels = cbvm.ProductViewModels;

            foreach (ProductViewModel p in productViewModels)
            {
                if (p.isSelected)
                {
                    mealBox.Products.Add(p.Product);
                    if (p.Product.ContainsAlcohol)
                    {
                        mealBox.IsEighteen = true;
                    }
                }

            }

            var createdMealBox = _repository.CreateMealBox(mealBox);
            if(createdMealBox == null)
            {
                ModelState.AddModelError("error", "An Error occured while Creating");
                return View();
            }

            return RedirectToAction("Admin", "Account");
        }

        public IActionResult Edit(int id)
        {
            var employee = _employeeRepository.GetEmployeeByNr(User.Identity!.Name!);
            ViewBag.CantinaServesWarm = employee?.Cantina.ServesWarm;

            MealBox? mealbox = _repository.GetMealBoxById(id);
            if (mealbox == null)
            {
                return NotFound();
            }

            List<ProductViewModel> productViewModels = new List<ProductViewModel>();
            foreach (Product p in _productRepository.Products)
            {
                if (mealbox.Products.Contains(p))
                {
                    productViewModels.Add(new ProductViewModel { Product = p, isSelected = true });
                } else
                {
                    productViewModels.Add(new ProductViewModel { Product = p, isSelected = false });
                }
            }

            var viewModel = new CreateUpdateMealBoxViewModel
            {
                MealBox = mealbox,
                ProductViewModels = productViewModels,
            };

            return View("EditBox", viewModel);
        }

        [HttpPost]
        public IActionResult Edit(CreateUpdateMealBoxViewModel cbvm)
        {
            MealBox? mealBox = cbvm.MealBox;
            mealBox.Products = new List<Product>();

            IList<ProductViewModel> productViewModels = cbvm.ProductViewModels;

            foreach (ProductViewModel p in productViewModels)
            {
                if (p.isSelected)
                {
                    mealBox.Products.Add(p.Product);
                    if (p.Product.ContainsAlcohol)
                    {
                        mealBox.IsEighteen = true;
                    }
                }

            }

            var updatedMealBox = _repository.EditMealBox(mealBox);
            if(updatedMealBox == null)
            {
                ModelState.AddModelError("error", "An Error occured while Updating");
                return View("EditBox");
            }

            return RedirectToAction("Admin", "Account");
        }

        [HttpPost]
        public IActionResult ReserveMealBox(int id)
        {
            var student = _studentRepository.GetStudentByEmail(User.Identity!.Name!);
            MealBox? mealBox = _repository.GetMealBoxById(id);

            try
            {
                _mealBoxReservationService.ReserveMealBox(student, mealBox, id);
            }
            catch (Exception e)
            {
                ModelState.AddModelError("ReservationError", e.Message);
                return View("MealBoxDetail", mealBox);
            }

            return RedirectToAction("Profile", "Account");
        }

    }
}

SSWFProject/Views/MealBox/ConfirmReservationModal.cshtml
@model MealBox

<div class="modal fade" id="reservationModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Wil Je Echt Reserveren?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body d-flex align-items-start">
                <button type="button" class="btn btn-lightgreen me-1" data-bs-dismiss="modal">Annuleren</button>
                <form asp-area="" asp-controller="MealBox" asp-action="ReserveMealBox" method="post" asp-route-id="@Model?.Id">
                    <input asp-for="@Model.Id" type="hidden" />
                    <button style="width:100%;" type="submit" class="btn btn-lightgreen">Reserveren</button>
                </form>
            </div>
        </div>
    </div>
</div>

SSWFProject/Views/MealBox/CreateBox.cshtml
@model CreateUpdateMealBoxViewModel
@{
    ViewData["Title"] = "Pakket Aanmaken";
    int productCount = 0;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SSWFProject.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://use.typekit.net/esv7sop.css">
</head>
<body>
    <div class="container-fluid m-0 p-0">
        <div class="row breadcrumb-row mt-0 pt-0 ms-0">
            <nav aria-label="breadcrumb m-0 p-0">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="breadcrumb-item"><a asp-area="" asp-controller="Account" asp-action="EmployeeLogin">Medewerker Inlog</a></li>
                    <li class="breadcrumb-item"><a asp-area="" asp-controller="Account" asp-action="Admin">Admin</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Pakket Aanmaken</li>
                </ol>
            </nav>
        </div>
    </div>

    <div class="container mt-2" style="min-height:469px">
        <div class="row justify-content-start me-0">
            <div class="col col-lg-5">
                <h1 class="mb-0">Pakket Aanmaken</h1>
                <p>
                    Op deze pagina kunt u een pakket aanmaken door de benodigde informatie in het formulier in te vullen en op de "aanmaak" knop te klikken.
                </p>
                <a class="btn btn-lightgreen" asp-area="" asp-controller="Account" asp-action="Admin" style="width: 25%;">Terug</a>
            </div>
        </div>

        <hr class="mt-3" />

        <div class="row create-form-row shadow mt-5 mb-5">
            <div class="row create-form-row-inner m-3">
                <form asp-action="Create" asp-controller="MealBox" method="post" class="row gy-2">
                    <div class="col md-6">
                        <div class="row">
                            <div class="col-md-6">
                                <label asp-for="@Model.MealBox.Name" class="form-label mb-0 pb-0">Naam</label>
                                <input asp-for="@Model.MealBox.Name" type="text" class="form-control" placeholder="Typ hier...">
                                <span asp-validation-for="@Model.MealBox.Name" class="text-danger"></span>
                            </div>
                            <div class="col-md-6">
                                <label asp-for="@Model.MealBox.Price" class="form-label mb-0 pb-0">Prijs</label>
                                <input asp-for="@Model.MealBox.Price" class="form-control" placeholder="Typ hier...">
                                <span asp-validation-for="@Model.MealBox.Price" class="text-danger"></span>
                            </div>
                            <div class="col-md-6">
                                <label asp-for="@Model.MealBox.City" class="form-label mt-2 mb-0 pb-0">Stad</label>
                                <select asp-for="@Model.MealBox.City" class="form-select" disabled>
                                    <option selected="selected" value="@ViewBag.CreateCityChoice">@ViewBag.CreateCityChoice</option>
                                </select>
                            </div>
                            <div class="col-md-6">
                                <label asp-for="@Model.MealBox.Cantina" class="form-label mt-2 mb-0 pb-0">Kantine</label>
                                <select class="form-select" disabled>
                                    <option selected="selected" value="@ViewBag.CreateLocationChoice">@ViewBag.CreateLocationChoice</option>
                                </select>
                            </div>
                            <div class="col-md-6">
                                <label asp-for="@Model.MealBox.PickupUntilTime" class="form-label mt-2 mb-0 pb-0">Ophaal Datum en Tijd</label>
                                <input asp-for="@Model.MealBox.PickupUntilTime" class="form-control" type="datetime-local" min="@DateTime.Now.ToString("yyyy-MM-dd'T'HH:mm")" max="@DateTime.Now.AddDays(2).ToString("yyyy-MM-dd'T'HH:mm")">
                                <span asp-validation-for="@Model.MealBox.PickupUntilTime" class="text-danger"></span>
                            </div>
                            <div class="col-md-6">
                                <label asp-for="@Model.MealBox.Type" class="form-label mt-2 mb-0 pb-0">Type Maaltijd</label>
                                <select asp-for="@Model.MealBox.Type" class="form-select" asp-items="Html.GetEnumSelectList<MealType>()" id="MealType">
                                    <option selected="selected" value="">Selecteer maaltijdtype</option>
                                    <span asp-validation-for="@Model.MealBox.Type" class="text-danger"></span>
                                </select>
                            </div>
                            <div class="col-md-6">
                                <div class="form-check">
                                    @if(ViewBag.CantinaServesWarm){
                                        <input asp-for="@Model.MealBox.IsWarm" class="form-check-input mt-2 mb-0 pb-0" type="checkbox" id="flexCheckDefault">
                                        <label asp-for="@Model.MealBox.IsWarm" class="form-check-label mt-2 mb-0 pb-0" for="flexCheckDefault">
                                            Pakket is warm
                                        </label>
                                    } else {
                                        <input asp-for="@Model.MealBox.IsWarm" class="form-check-input mt-2 mb-0 pb-0" type="checkbox" disabled>
                                        <label asp-for="@Model.MealBox.IsWarm" class="form-check-label mt-2 mb-0 pb-0">
                                            Pakket is warm
                                        </label>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col md-6">
                        <div class="container product-container shadow">
                            @foreach (ProductViewModel pvm in Model?.ProductViewModels ?? Enumerable.Empty<ProductViewModel>())
                            {
                                <div class="card productpicker-card p-0 m-3 h-100 shadow">
                                    <div class="row g-0">
                                        <div class="col-md-4">
                                            <img src="@Url.Content(pvm.Product.ImgUrl)" class="img-fluid rounded-start detail-card-img" alt="Product Image">
                                        </div>
                                        <div class="col-md-8">
                                            <div class="card-body">
                                                <div class="col-md-6 m-0">
                                                    <h4 class="card-title mb-0">@pvm.Product.Name</h4>
                                                    @if (pvm.Product.ContainsAlcohol)
                                                    {
                                                        <p class="card-text">Bevat Alcohol</p>
                                                    }
                                                    else
                                                    {
                                                        <p class="card-text">Bevat Geen Alcohol</p>
                                                    }
                                                </div>
                                                <div class="col-md-6 m-0">
                                                    <input asp-for="@Model.ProductViewModels[productCount].Product.Name" value="@pvm.Product.Name" type="hidden">
                                                    <input asp-for="@Model.ProductViewModels[productCount].Product.ContainsAlcohol" value="@pvm.Product.ContainsAlcohol" type="hidden">
                                                    <input asp-for="@Model.ProductViewModels[productCount].Product.ImgUrl" value="@pvm.Product.ImgUrl" type="hidden">
                                                    <input asp-for="@Model.ProductViewModels[productCount].Product.Id" value="@pvm.Product.Id" type="hidden">
                                                    <input asp-for="@Model.ProductViewModels[productCount].isSelected" type="checkbox">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                productCount++;
                            }
                        </div>
                    </div>
                    <div class="col-12 mt-3">
                        <button type="submit" class="btn btn-brown">Aanmaken</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
</body>
</html>

SSWFProject/Views/MealBox/EditBox.cshtml
@model CreateUpdateMealBoxViewModel
@{
    ViewData["Title"] = "Pakket Wijzigen";
    int productCount = 0;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SSWFProject.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://use.typekit.net/esv7sop.css">
</head>
<body>
    <div class="container-fluid m-0 p-0">
        <div class="row breadcrumb-row mt-0 pt-0 ms-0">
            <nav aria-label="breadcrumb m-0 p-0">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="breadcrumb-item"><a asp-area="" asp-controller="Account" asp-action="EmployeeLogin">Medewerker Inlog</a></li>
                    <li class="breadcrumb-item"><a asp-area="" asp-controller="Account" asp-action="Admin">Admin</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Pakket Wijzigen</li>
                </ol>
            </nav>
        </div>
    </div>

    <div class="container mt-2" style="min-height:469px">
        <div class="row justify-content-start me-0">
            <div class="col col-lg-5">
                <h1 class="mb-0">Pakket Wijzigen</h1>
                <p>
                    Op deze pagina kunt u een bestaand pakket wijzigen door de benodigde informatie in het formulier in te vullen en op de "wijzigen" knop te klikken.
                </p>
                <a class="btn btn-lightgreen" asp-area="" asp-controller="Account" asp-action="Admin" style="width: 25%;">Terug</a>
            </div>
        </div>

        <hr class="mt-3" />

        <div class="row create-form-row shadow mt-5 mb-5">
            <div class="row create-form-row-inner m-3">
                <form asp-action="Edit" asp-controller="MealBox" method="post" class="row gy-2">
                    <div class="col md-6">
                        <div class="row">
                            <div class="col-md-6">
                                <label asp-for="@Model.MealBox.Name" class="form-label mb-0 pb-0">Naam</label>
                                <input asp-for="@Model.MealBox.Name" type="text" class="form-control" placeholder="Typ hier...">
                                <input asp-for="@Model.MealBox.Id" type="hidden" class="form-control" placeholder="Typ hier...">
                            </div>
                            <div class="col-md-6">
                                <label asp-for="@Model.MealBox.Price" class="form-label mb-0 pb-0">Prijs</label>
                                <input asp-for="@Model.MealBox.Price" class="form-control" placeholder="Typ hier...">
                            </div>
                            <div class="col-md-6">
                                <label asp-for="@Model.MealBox.City" class="form-label mt-2 mb-0 pb-0">Stad</label>
                                <select asp-for="@Model.MealBox.City" class="form-select" disabled>
                                    <option selected="selected">@Model.MealBox.City</option>
                                </select>
                            </div>
                            <div class="col-md-6">
                                <label asp-for="@Model.MealBox.Cantina.Location" class="form-label mt-2 mb-0 pb-0">Kantine</label>
                                <select asp-for="@Model.MealBox.Cantina.Location" class="form-select" disabled>
                                    <option selected="selected">@Model.MealBox.Cantina.Location</option>
                                </select>
                            </div>
                            <div class="col-md-6">
                                <label asp-for="@Model.MealBox.PickupUntilTime" class="form-label mt-2 mb-0 pb-0">Ophaal Datum en Tijd</label>
                                <input asp-for="@Model.MealBox.PickupUntilTime" class="form-control" type="datetime-local" value="@Model.MealBox.PickupUntilTime.Value.ToString("yyyy-MM-dd'T'HH:mm")" min="@DateTime.Now.ToString("yyyy-MM-dd'T'HH:mm")" max="@DateTime.Now.AddDays(2).ToString("yyyy-MM-dd'T'HH:mm:ss")">
                            </div>
                            <div class="col-md-6">
                                <label asp-for="@Model.MealBox.Type" class="form-label mt-2 mb-0 pb-0">Type Maaltijd</label>
                                <select asp-for="@Model.MealBox.Type" class="form-select" asp-items="Html.GetEnumSelectList<MealType>()" id="MealType">
                                </select>
                            </div>
                            <div class="col-md-6">
                                <div class="form-check">
                                    @if (ViewBag.CantinaServesWarm)
                                    {
                                        <input asp-for="@Model.MealBox.IsWarm" class="form-check-input mt-2 mb-0 pb-0" type="checkbox" id="flexCheckDefault">
                                        <label asp-for="@Model.MealBox.IsWarm" class="form-check-label mt-2 mb-0 pb-0" for="flexCheckDefault">
                                            Pakket is warm
                                        </label>
                                    }
                                    else
                                    {
                                        <input asp-for="@Model.MealBox.IsWarm" class="form-check-input mt-2 mb-0 pb-0" type="checkbox" disabled>
                                        <label asp-for="@Model.MealBox.IsWarm" class="form-check-label mt-2 mb-0 pb-0">
                                            Pakket is warm
                                        </label>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col md-6">
                        <div class="container product-container shadow">
                            @foreach (ProductViewModel pvm in Model?.ProductViewModels ?? Enumerable.Empty<ProductViewModel>())
                            {
                                <div class="card productpicker-card p-0 m-3 h-100 shadow">
                                    <div class="row g-0">
                                        <div class="col-md-4">
                                            <img src="@Url.Content(pvm.Product.ImgUrl)" class="img-fluid rounded-start detail-card-img" alt="Product Image">
                                        </div>
                                        <div class="col-md-8">
                                            <div class="card-body">
                                                <div class="col-md-6 m-0">
                                                    <h4 class="card-title mb-0">@pvm.Product.Name</h4>
                                                    @if (pvm.Product.ContainsAlcohol)
                                                    {
                                                        <p class="card-text">Bevat Alcohol</p>
                                                    }
                                                    else
                                                    {
                                                        <p class="card-text">Bevat Geen Alcohol</p>
                                                    }
                                                </div>
                                                <div class="col-md-6 m-0">
                                                    <input asp-for="@Model.ProductViewModels[productCount].Product.Name" value="@pvm.Product.Name" type="hidden">
                                                    <input asp-for="@Model.ProductViewModels[productCount].Product.ContainsAlcohol" value="@pvm.Product.ContainsAlcohol" type="hidden">
                                                    <input asp-for="@Model.ProductViewModels[productCount].Product.ImgUrl" value="@pvm.Product.ImgUrl" type="hidden">
                                                    <input asp-for="@Model.ProductViewModels[productCount].Product.Id" value="@pvm.Product.Id" type="hidden">
                                                    <input asp-for="@Model.ProductViewModels[productCount].isSelected" type="checkbox">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                productCount++;
                            }
                        </div>
                    </div>
                    <div class="col-12 mt-3">
                        <button type="submit" class="btn btn-brown">Wijzigen</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
</body>
</html>

SSWFProject/Views/MealBox/MealBoxDetail.cshtml
@model MealBox
@{
    ViewData["Title"] = "Pakket Details";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SSWFProject.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://use.typekit.net/esv7sop.css">
</head>
<body>
    <div class="container-fluid m-0 p-0">
        <div class="row breadcrumb-row mt-0 pt-0 ms-0">
            <nav aria-label="breadcrumb m-0 p-0">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="breadcrumb-item"><a asp-area="" asp-controller="MealBox" asp-action="MealBoxes">Pakketten</a></li>
                    <li class="breadcrumb-item active" aria-current="page">@Model.Name</li>
                </ol>
            </nav>
        </div>
    </div>

    <div class="container" style="min-height:469px">
        <div class="row me-0">
            <div class="col-sm-12 col-md-4 col-lg-8">
                <h1 class="m-0">@Model?.Name</h1>
                @if(Model.IsWarm){
                    <h3 class="mealdetail-header">@Model?.Type (Warm)</h3>
                } else {
                    <h3 class="mealdetail-header">@Model?.Type</h3>
                }
                <h3 class="mealdetail-header">@Model?.City, @Model?.Cantina.Location</h3>
                <h3 class="mealdetail-header">€ @Model?.Price</h3>
            </div>
            <div class="col reservation-col shadow mt-3 col-lg-4">
                <div class="row">
                    <div class="col lg-8 m-3">
                        <h4 class="mb-0">Ophalen:</h4>
                        <h5>Van: @Model?.PickupFromTime.Value.ToString("MM/dd/yyyy HH:mm")</h5>
                        <h5>Tot: @Model?.PickupUntilTime.Value.ToString("MM/dd/yyyy HH:mm")</h5>
                    </div>
                    <div class="col col-lg-4 d-flex justify-content-center me-2">
                        @if(User.HasClaim("UserType", "studentuser")){
                            <button class="btn btn-brown my-auto shadow" data-bs-toggle="modal" data-bs-target="#reservationModal">Reserveren</button>
                            <partial name="ConfirmReservationModal" model="@Model"></partial>
                        } else {
                            <button class="btn btn-brown my-auto shadow" disabled>Reserveren*</button>
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 d-flex justify-content-end mt-2">
                @if (!User.HasClaim("UserType", "studentuser"))
                {
                    <p me-0>*Kan alleen reserveren als je ingelogd bent als student</p>
                }
                <span class="text-danger"> @Html.ValidationMessage("ReservationError")</span>
            </div>
        </div>
        <div class="row">
            <h2 class="mt-5 mb-0">Producten</h2>
        </div>

        <hr class="mt-2">

        <div class="row row-cols-1 row-cols-md-2 mt-4">
            @foreach (Product p in Model?.Products ?? Enumerable.Empty<Product>())
            {
                <div class="card detail-card p-0 m-3 h-100 shadow">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="@Url.Content(p.ImgUrl)" class="img-fluid rounded-start detail-card-img" alt="Product Image">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h4 class="card-title">@p.Name</h4>
                                @if(p.ContainsAlcohol){
                                    <p class="card-text">Bevat Alcohol</p>
                                } else {
                                    <p class="card-text">Bevat Geen Alcohol</p>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>

</body>
</html>